osism/osism.github.io

- docs/guides/deploy-guide/manager.md
Guides ([guides](https://osism.github.io/docs/guides/) & [advanced guides](https://osism.github.io/docs/advanced-guides/)) that will be consumed by the [SCS Documentation ](https://docs.scs.community) should be absolute as relative links cannot be resolved if the paths are not within the imported paths. 
This PR fixes only one link to the configuration. 
Currently blocks building SCS Docs: https://github.com/SovereignCloudStack/docs/pull/115
> Make link absolute

- docs/guides/deploy-guide/examples/testbed.md
Looks like the <...> are not working like expected:
Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a link in MDX, use `[text](url)`)
Related to 7b7aa7feb7352b0244270b4f590cd2ab65866dd2
> testbed: fix syntax in the webinterfaces table

- docs/guides/other-guides/testbed.md
The paragraph `Usage the Openstack CLI` explains how to access the cloud running the testbed, but not the testbed itself.
The documentation is adapted to reference the files in `environments/openstack` to access the testbed.
> Fix docs for testbed access via openstack cli

- docs/guides/deploy-guide/services/ceph.md
> ceph: add ceph_kolla_keys parameter

- docs/guides/configuration-guide/configuration-repository.md
Related to osism/cfg-cookiecutter#598
> cookiecutter: use a single network for ceph frontend & backend

- docs/guides/operations-guide/openstack/day2-operations/image-manager/index.md
- docs/guides/operations-guide/openstack/day2-operations/image-manager/update.md
added path image-manager , change image-manager.md to index.md  to presave the original path.
added update.md for update.py  and described the role of it to modify exisiting yaml files from the repo.
updated cirros and ubuntu verions in image-manager docs to a more actual version.
> Openstack image manager doc update

- docs/guides/configuration-guide/services/docker.md
> Add docker configuration guide

- docs/guides/other-guides/testbed.mdx
The `haproxy_user` defaults to 'openstack' ([1]).
[1]
https://github.com/osism/defaults/blob/main/all/001-kolla-defaults.yml#L972
> Change haproxy_user in testbed documentation

- docs/guides/operations-guide/openstack/octavia.md
> operations-guide: SSH access to amphorae

- docs/guides/deploy-guide/services/openstack.md
The procedure was accidentally introduced with commit
3843cde6d9c724cd08034b1ef13389e2a47dcb9c at Tue Jul 9 09:20:47
where the motivation was that we can support a encrypted secure.yml.
We changed our strategy that we want to create the access based on the
configuration data.
> remove incorrect procedure

- docs/guides/deploy-guide/services/openstack.md
The procedure was accidentally introduced with commit 3843cde6d9c724cd08034b1ef13389e2a47dcb9c
where the motivation was that we can support a encrypted secure.yml. 
Missed another command in the previous request.
> remove incorrect procedure (#647)

- docs/guides/configuration-guide/rook.md
To reflect the changes made to the installation of the cephclient this change was made.
A new type of the cehpclient (`rook`) is introduced and when set the installation of the cephclient will utilise the tolling provided by Rook and checks if there is a previous installation of cephclient wrappers (`package` or `container`). If that is the case the previous installation is properly cleaned up before installing the new wrapper scripts appropriate to the Rook environment.
[osism/issues/886](https://github.com/osism/issues/issues/886)
[osism/issues/1038](https://github.com/osism/issues/issues/1038)
> Adapt to current behaviour of cepchclient installation

- docs/guides/other-guides/cloud-in-a-box/running-on-a-virtual-machine.md
Added VirtualBox configuration for runing Ciab
> Ciab virtualbox

- docs/guides/upgrade-guide/manager.mdx
> upgrade-guide: ansible vault auto detect works for OSISM >= 8.0.0

- docs/guides/configuration-guide/rookify.md
- docs/guides/deploy-guide/rookify.md
- docs/guides/deploy-guide/services/rookify.md
- docs/guides/operations-guide/rookify.md
- docs/guides/troubleshooting-guide/rookify.md
- adding docs for rookify: deploy, config and operation guides
> feat: add guide docs for rookify

- docs/guides/deploy-guide/examples/cloud-in-a-box.md
- docs/guides/deploy-guide/examples/index.md
- docs/guides/deploy-guide/examples/testbed.md
The examples are only pointers to the Testbed & Cloud in a Box guides.
> deploy-guide: remove examples

- docs/guides/user-guide/openstack/install-instance-from-iso.md
Creating instances with blank nova local storage is not supported ([1]). The documentation for installation from ISO is adapted to refelct that.
[1]
https://bugs.launchpad.net/nova/+bug/2090926/comments/1
> Update install from ISO docs

- docs/testbed.mdx
We will add it again later when the Keycloak integration has been revised.
> Remove keycloak integration from testbed

- docs/guides/operations-guide/network.md
Part of https://github.com/osism/issues/issues/1214
Part of https://github.com/osism/issues/issues/1215
> Add operations docs for applying network changes

- docs/guides/operations-guide/package-upgrades.md
Add a package upgrade guide for compute nodes using `osism` commands to the operations guide.
> Add package upgrade docs to ops guide
