docs/guides/configuration-guides/ceph.md
docs/guides/configuration-guides/keystone-oidc-federation.md
docs/guides/configuration-guides/keystone.md

configuration: add ceph swappiness

---

docs/advanced-guides/testbed.md

testbed: how to fix "unsupported locale setting"

---

docs/guides/upgrade-guides/docker.md

upgrade-guides: add docker

---

docs/guides/upgrade-guides/docker.md

upgrade-guides: add docker version

---

docs/guides/operations-guide/ceph.md

Refactor Ceph documentation
Relates to the following issues:
https://github.com/osism/issues/issues/642
https://github.com/osism/issues/issues/563
https://github.com/osism/issues/issues/564
https://github.com/osism/issues/issues/647
https://github.com/osism/issues/issues/637
Signed-off-by: Paul-Philipp Kuschy <kuschy@osism.tech>

Refactor Ceph documentation

---

docs/guides/deploy-guide/index.md
docs/guides/deploy-guide/infrastructure.md
docs/guides/deploy-guide/logging-monitoring.md
docs/guides/upgrade-guides/index.md
docs/guides/upgrade-guides/infrastructure.md
docs/guides/upgrade-guides/logging-monitoring.md

* common
* prometheus
* redis
* memcached

deploy/upgrad: add some more services

---

docs/guides/deploy-guide/manager.md

Migrate "Manager node" deployment docs

---

docs/guides/upgrade-guides/docker.md

Do nut upgrade docker on the manager with osism apply docker

---

docs/guides/operations-guide/manager/task.md

Related to osism/osism.github.io#57

How to reset the manager redis

---

docs/guides/upgrade-guides/docker.md

It is not a good idea to change the serial default of the docker play

---

docs/guides/configuration-guides/inventory.md

Add inventory to the configuraton guides

---

docs/guides/deploy-guide/infrastructure.md
docs/guides/upgrade-guides/infrastructure.md

Deploy & upgrade loadbalancer

---

docs/guides/deploy-guide/infrastructure.md
docs/guides/upgrade-guides/infrastructure.md

Deploy & upgrade rabbitmq & mariadb

---

docs/guides/deploy-guide/openstack.md
docs/guides/upgrade-guides/openstack.md

Deploy & upgrade horizon

---

docs/advanced-guides/cloud-in-a-box.md

- add a more detailed installation procedure
- change the login name from "dragon" to "osism"
- beautify md syntax
- minor improvements in the wording

Documentation improvements

---

docs/guides/configuration-guides/inventory.md

configuration: define variable for all nodes

---

docs/guides/deploy-guide/ceph.md

Use kolla-ceph-rgw play

---

docs/guides/configuration-guides/ceph.md

Document how to use self-signed certs with ceph rgw service

---

docs/guides/configuration-guides/self-signed-certificates.md

Add self-signed certificates to configuration guide

---

docs/advanced-guides/cloud-in-a-box.md

improve documentation

---

docs/advanced-guides/testbed.md

testbed: mention deploy time

---

docs/advanced-guides/testbed.md

testbed: add ci jobs

---

docs/guides/configuration-guides/manager.md

manager: add opensearch_protocol parameter

---

docs/advanced-guides/developer-guide/index.md
docs/advanced-guides/developer-guide/releases.md
docs/advanced-guides/developer-guide/scripts.md

Add change.sh & change-osism.sh script

---

docs/guides/configuration-guides/manager.md

Describe how to use a specific version of osism/cfg-generics

---

docs/guides/configuration-guides/network.md

Add network configuration guide

---

docs/guides/configuration-guides/openstack/index.md

Add list of network interfaces usable with Kolla

---

docs/advanced-guides/cloud-in-a-box.md

Depends on https://github.com/osism/cloud-in-a-box/pull/179 and https://github.com/osism/node-image/pull/74.
Merge these at first.

add development documentation

---

docs/advanced-guides/style-guide.md

Signed-off-by :Sebastian Neumann <neumann@b1-systems.de>

Explain Black in docs/style-guide.md

---

docs/guides/deploy-guide/services/ceph.md

Fix broken relative link

---

docs/guides/deploy-guide/examples/cloud-in-a-box.md

Related to osism/cloud-in-a-box#182

cloud-in-a-box: add Ceph dashboard

---

docs/guides/configuration-guide/openstack/index.md

Pin openstack images

---

docs/guides/configuration-guide/openstack/nova.md

Reserve compute node resources

---

docs/guides/operations-guide/openstack/cinder.md

operations-guide: sync cinder quota

---

docs/guides/deploy-guide/examples/testbed.md

testbed: fix URLs

---

docs/guides/deploy-guide/examples/testbed.md

testbed: add haproxy dashboard URLs

---

docs/guides/operations-guide/openstack/cinder.md

openstack: add volume qos policies

---

docs/guides/configuration-guide/openstack/keystone.md

configuration-guide: sync domain-manager policy

---

docs/guides/configuration-guide/configuration-repository.md
docs/guides/upgrade-guide/manager.md

Use gilt < v2

---

docs/guides/configuration-guide/openstack/nova.md

Related to 066ca1c9f3cb7a65ba4ba55b08c131f59df88a6f

Explain directory names

---

docs/guides/deploy-guide/examples/testbed.md

Signed-off-by: Sven Kieske <kieske@osism.tech>

fix small typo and some mdlint stuff in testbed docs

---

docs/guides/configuration-guide/ceph.md

ceph: improve the LVM2 configuration samples

---

docs/guides/other-guides/cloud-in-a-box.md
docs/guides/other-guides/testbed.md

Related to osism/osism.github.io#310

Fix wireguard.com link

---

docs/guides/operations-guide/openstack/day2-operations/resource-manager.md

also fix some markdownlint issues around code blocks
Signed-off-by: Sven Kieske <kieske@osism.tech>

fix typo in resource manager docs

---

docs/guides/configuration-guide/openstack/keystone.md

Rename domain-manager role to manager

---

docs/guides/other-guides/testbed.md

Document bootstrap of openstack resources and check with refstack in the manual testbed deployment steps.

Document manual bootstrap and check of testbed installation

---

blog/2024-01-11-kubernetes-service-deployments.md
blog/2024-01-12-restart-of-a-container-on-a-specific-node.md
blog/2024-01-16-switch-to-opentofu.md

Part of https://github.com/osism/issues/issues/927

Replace osism.github.io with osism.tech

---

docs/guides/configuration-guide/configuration-repository.md

Set TARGET_UID when using the cookiecutter container

---

docs/guides/deploy-guide/services/ceph.md

Use ceph-pools play to create ceph pools

---

docs/guides/configuration-guide/openstack/aodh.md
docs/guides/configuration-guide/openstack/barbican.md
docs/guides/configuration-guide/openstack/ceilometer.md
docs/guides/configuration-guide/openstack/cinder.md
docs/guides/configuration-guide/openstack/designate.md
docs/guides/configuration-guide/openstack/glance.md
docs/guides/configuration-guide/openstack/heat.md
docs/guides/configuration-guide/openstack/horizon.md
docs/guides/configuration-guide/openstack/ironic.md
docs/guides/configuration-guide/openstack/keystone.md
docs/guides/configuration-guide/openstack/magnum.md
docs/guides/configuration-guide/openstack/manila.md
docs/guides/configuration-guide/openstack/neutron.md
docs/guides/configuration-guide/openstack/nova.md
docs/guides/configuration-guide/openstack/octavia.md
docs/guides/configuration-guide/openstack/placement.md
docs/guides/configuration-guide/openstack/skyline.md

Part of https://github.com/osism/issues/issues/938

Add simple configuration guides for all supported OpenStack services

---

docs/guides/configuration-guide/commons/network.md

network: Add the network_allow_service_restart parameter

---

docs/guides/deploy-guide/services/ceph.mdx

Related to osism/issues#935
Related to osism/issues#896

ceph: add parameters to skip & throttle service restarts

---

docs/guides/deploy-guide/services/ceph.mdx

Related to c7485921a9fc528a8cb081d4c3c1f506405b4f77

Some more details

---

docs/guides/operations-guide/openstack/day2-operations/project-manager.md

Add initial Openstack Project Manager Documentation

Docs openstack project manager

---

docs/guides/troubleshooting-guide/manager.md

Related to osism/issues#734
Related to osism/issues#976

Improve the manager reset in the troubleshooting guide

---

docs/guides/configuration-guide/proxy.md

Improve the proxy configuration

---

docs/guides/operations-guide/openstack/day2-operations/simple-stress.md

Release of the inital Simple Stress Test Documentation

Openstack simple stress doc

---

docs/guides/deploy-guide/services/openstack.md
docs/guides/upgrade-guide/openstack.md

openstack: add manage octavia image commands

---

docs/guides/operations-guide/index.md

Reboot of nodes

---

docs/guides/configuration-guide/ceph.md

Document how to configure a 2nd ceph cluster

---

.gitignore
docs/guides/other-guides/openstack-health-monitor.md
docs/guides/user-guide/openstack/security-groups.md
docs/guides/user-guide/openstack/user-data-backups.md

This way the files will always be available. We have to update them from time to time. In the CI we will do this on every build.

Persist external files

---

docs/guides/configuration-guide/ceph.md

Part of https://github.com/osism/issues/issues/1013

Document loadbalancer integration of ceph dashboard

---

docs/guides/operations-guide/openstack/index.md

operations-guide: remove all network services of a removed compute node

---

docs/release-notes/osism-7.md

Mention octavia valid interfaces in the release notes

---

docs/guides/configuration-guide/ceph.md

Add ceph reousce limit parameters

---

docs/guides/configuration-guide/ceph.md

Add ceph cpu & numa node pinning

---

docs/release-notes/osism-7.md

Related to c233c9a4adec8e7730cb9378eb890ad30e80b3f8

release-notes: fix a few nits

---

docs/guides/configuration-guide/configuration-repository.md

Fix links in configuration repository file

---

docs/guides/configuration-guide/manager.mdx
docs/guides/upgrade-guide/manager.mdx

relative paths cannot be resolved by scs docs and breaks build: https://github.com/SovereignCloudStack/docs/actions/runs/9278214191/job/25528866433

Make links absolute

---

docs/guides/operations-guide/ceph.md

How to remove all OSDs of a Ceph node

---

docs/guides/concept-guide/hardware-bom.md
docs/guides/concept-guide/index.md

Partially based on SovereignCloudStack/docs#188

concept-guide: add node descriptions

---

docs/guides/other-guides/openrc-clouds.md
docs/guides/user-guide/openstack/openstackclient.md

PR for issue: https://github.com/osism/issues/issues/1043

doc for openrc to clouds.yaml

---

docs/guides/configuration-guide/configuration-repository.md

Depends on https://github.com/osism/cfg-generics/pull/461

add documentation for secrets

---

docs/guides/operations-guide/infrastructure.md

operations-guide: add loadbalancer

---

docusaurus.config.js
package.json
yarn.lock

Trying to solve the search bar problems.

try to fix search

---

docs/release-notes/osism-7.md
src/pages/index.js

release-notes: add 7.1.0

---

docs/guides/other-guides/testbed.mdx

Part of https://github.com/osism/issues/issues/1085

Add `kolla_dev_mode` docs to testbed guide

---

docs/guides/other-guides/cloud-in-a-box/running-on-a-virtual-machine.md

Added specs how to setup a VM for Cloud in a Box on WMware vSphere/ESXi.

Running on a virtual machine - add VMware vSphere/ESXi

---

docs/guides/configuration-guide/ceph.md
docs/guides/operations-guide/ceph.md

Add how to deploy a new OSD service

---

docs/guides/configuration-guide/rook.md
docs/guides/deploy-guide/services/rook.md

Part of [osism/issues#1084](https://github.com/osism/issues/issues/1084)
Part of [osism/issues#886](https://github.com/osism/issues/issues/886)

Add documentation changing labels regarding rook

---

docs/guides/other-guides/testbed.mdx

This depends on https://github.com/osism/testbed/pull/2496

Document existence of artcodix environment profile.

---

docs/guides/deploy-guide/manager.md
docs/guides/deploy-guide/seed.md

Minimal improvments and a missing dependency.

manager deployment

---

docs/guides/user-guide/openstack/install-instance-from-iso.md

Add user guide for crearting and installing instances from ISOs in OpenStack using the rescue mode.

Document installing from ISOs in OpenStack

---

blog/2024-01-11-kubernetes-service-deployments.md
blog/2024-01-16-switch-to-opentofu.md
docs/guides/other-guides/testbed.mdx
docusaurus.config.js

scs.community will be archived.

Use sovereigncloudstack.org

---

docs/guides/configuration-guide/openstack/nova.md

Part of https://github.com/osism/issues/issues/1195

Add documentation to back instance memory by hugepages

---

docusaurus.config.js

Add open issue link

---

docs/guides/other-guides/cloud-in-a-box/index.md

Part of osism/cloud-in-a-box#336

cloud-in-a-box: improve & add /etc/hosts entries

---

docs/guides/operations-guide/network.md

Part of https://github.com/osism/issues/issues/792

Add OVN L3HA documentation

---

docs/appendix/networks.md

dnsmasq used network mode host.

Use dnsmasq_network for the new httpd service

---

docs/cloud-in-a-box/running-on-a-virtual-machine.md

* Booting required EFI BIOS in my environment.
* virtio-scsi is required to ensure the disk is /dev/sda and the EFI firmware can boot from it.

Recommend EFI and SCSI (virtio-scsi) for KVM.

---

docs/guides/concept-guide/components/netdata.md
docs/guides/concept-guide/components/openstack.md.x

concept-guide: add netdata
